### ISSUE TITLE
Simple Code Snippets to load different datasets

### ISSUE THREAD

**Issue by Karn3003** [bogdanraonic3/ConvolutionalNeuralOperator#2]
Hi,
It would be great if you can provide code snippets to load datasets from the h5 file for all different datasets. (As it helps how the dataset is stored and how we can split it into train, test set etc)

**Comment by bogdanraonic3** [comment]
I added explanations for data loaders for each dataset class (in the file Problems/CNOBenchmarks.py). 
There is also a new Zenodo link with compressed (~2.8gb) and better named datasets - https://zenodo.org/records/10058382
